#!/usr/bin/env node
/**
 * Regenerate `test/browser_e2e/spec_inventory.json` — the EXPECTED browser-suite inventory.
 *
 * WHY THIS EXISTS (track gate_coverage_20260912, Phase 0 deliverable; AC-3).
 *
 * The parent issue (`temp/archived/ISSUE_browser_e2e_gate_drift_20260912.md`) recorded 22 failing
 * browser cases that had accumulated across several releases with nobody noticing. The repair
 * (`a122be2`) fixed the cases; this file starts the fix for the way they hid — a suite that reports
 * a smaller green run when a spec file silently drops out of collection.
 *
 * The gate runner (Phase 2) therefore diffs the LIVE enumeration against this manifest: the spec
 * file LIST, per-file presence, and the test count per file. A missing OR unexpected file is a
 * FAILURE that names the file. That check is only honest if the expectation is a committed artifact
 * rather than a number typed into the runner — otherwise the assertion and the thing that makes it
 * pass get authored by the same change, which is how a guard becomes vacuous.
 *
 * WHY A GENERATOR AND NOT A HAND-WRITTEN JSON. A hand-typed 67-entry list rots the first time
 * someone renames a spec, and the rot is invisible until the gate misreports. This regenerates the
 * manifest from the suite's own collection, so the file is always reproducible — and regenerating is
 * a DELIBERATE act with a diff to review (which is the point: adding or removing a spec file should
 * show up in review, not slip through).
 *
 * PENDING IS DELIBERATELY ABSENT. The flag-gated capture/probe specs skip at RUNTIME (`this.skip()`
 * inside the test body), so a dry run reports `pending: 0` — MEASURED. The pending expectation
 * therefore cannot live here; it is read from a real run and recorded beside this manifest as
 * `test/browser_e2e/spec_pending.json` (see `--pending <results.json>`).
 *
 * USAGE
 *   node scripts/gen_spec_inventory.js                  # collect + write the manifest
 *   node scripts/gen_spec_inventory.js --dry-run-path P # use an existing dry-run JSON
 *   node scripts/gen_spec_inventory.js --pending R.json # ALSO write the pending map from a real run
 *
 * The `--pending` form reads a `--reporter json` result from an ACTUAL run and records which cases
 * are pending and under which harness, so "94 pending" stops being a number nobody can interpret.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const SPEC_DIR = path.join(ROOT, "test", "browser_e2e");
const OUT = path.join(SPEC_DIR, "spec_inventory.json");
const PENDING_OUT = path.join(SPEC_DIR, "spec_pending.json");

function arg(name) {
  const i = process.argv.indexOf(name);
  return i >= 0 && i + 1 < process.argv.length ? process.argv[i + 1] : null;
}

/** Every `.js` under test/browser_e2e, recursively — what `mocha --recursive` actually loads. */
function allJs(dir, rel) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const r = rel ? rel + "/" + e.name : e.name;
    if (e.isDirectory()) out.push(...allJs(path.join(dir, e.name), r));
    else if (e.name.endsWith(".js")) out.push(r);
  }
  return out;
}

/** Collect the suite WITHOUT executing it (a dry run still requires every spec file). */
function collect() {
  const given = arg("--dry-run-path");
  if (given) return JSON.parse(fs.readFileSync(given, "utf8"));
  const out = execFileSync(
    process.execPath,
    [
      path.join(ROOT, "node_modules", "mocha", "bin", "mocha.js"),
      "test/browser_e2e",
      "--recursive",
      "--dry-run",
      "--reporter",
      "json",
      "--timeout",
      "900000",
    ],
    { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  );
  return JSON.parse(out);
}

function main() {
  const dry = collect();

  // Group the collected tests by the file that defines them. `file` is present per test in mocha
  // 11's json reporter (verified) — the grouping is by basename because that is the stable identity.
  const byFile = new Map();
  for (const t of dry.tests) {
    const k = path.basename(t.file || "(none)");
    if (!byFile.has(k)) byFile.set(k, []);
    byFile.get(k).push(t.fullTitle);
  }

  const loaded = allJs(SPEC_DIR, "").sort();
  const defining = [...byFile.keys()].sort();
  const loaderOnly = loaded.filter((f) => !byFile.has(path.basename(f)));

  const manifest = {
    _comment:
      "The EXPECTED browser-suite inventory, diffed by the gate runner so a spec file that drops " +
      "out of collection is a FAILURE that names the missing file, not a smaller green run. " +
      "Generated by scripts/gen_spec_inventory.js — regenerate DELIBERATELY, and say why in the commit.",
    provenance: {
      produced_by: "node scripts/gen_spec_inventory.js",
      collects_with: "mocha test/browser_e2e --recursive --dry-run --reporter json",
      measured_at: new Date().toISOString().slice(0, 10),
      tracked_by: "conductor/tracks/gate_coverage_20260912 (Phase 0 deliverable; asserted by AC-3)",
      pending_is_runtime:
        "A dry run CANNOT see the pending set: the flag-gated capture/probe specs skip at RUNTIME " +
        "(this.skip() inside the test body), so `stats.pending` is 0 here — MEASURED. The pending " +
        "expectation lives beside this file in spec_pending.json, read from a REAL run.",
    },
    expected: {
      loaded_js_files: loaded.length,
      spec_files: defining.length,
      tests_collected: dry.tests.length,
    },
    spec_files: defining.map((f) => ({ file: f, tests: byFile.get(f).length })),
    loader_only_files: loaderOnly,
  };
  fs.writeFileSync(OUT, JSON.stringify(manifest, null, 2) + "\n");
  console.log(
    `wrote ${path.relative(ROOT, OUT)}: ${defining.length} spec files, ` +
      `${dry.tests.length} tests collected, ${loaded.length} .js loaded ` +
      `(${loaderOnly.length} loader-only)`,
  );

  // OPTIONAL: the pending map, from a real `--reporter json` run.
  const pendingPath = arg("--pending");
  if (pendingPath) {
    const real = JSON.parse(fs.readFileSync(pendingPath, "utf8"));
    // NOTE: mocha's json reporter keeps pending cases in their OWN top-level array — they are NOT
    // filtered out of `tests`, but `tests` carries no per-test pending flag either, so reading
    // `tests.filter(t => t.pending)` silently yields ZERO. Measured and fixed 2026-09-12: the first
    // version of this function did exactly that and wrote `case_count: 0` against a run whose own
    // stats said `pending: 94` — the precise "a guard that reports a reassuring number" defect this
    // track exists to remove. Read the top-level array.
    const pending = real.pending || [];
    const bySpec = {};
    for (const t of pending) {
      const f = path.basename(t.file || "(none)");
      (bySpec[f] = bySpec[f] || []).push(t.fullTitle);
    }
    const map = {
      _comment:
        "The pending expectation, read from a REAL run — a dry run cannot see these, because the " +
        "flag-gated specs skip at runtime (this.skip() in the body). `case_count` is asserted so a " +
        "spec that STOPS skipping (and starts running, or fails) shows up as a change rather than a " +
        "quieter gate, and so does one that starts skipping for a new reason.",
      provenance: {
        produced_by: "node scripts/gen_spec_inventory.js --pending <results.json>",
        read_from: path.basename(pendingPath),
        measured_at: new Date().toISOString().slice(0, 10),
        tracked_by: "conductor/tracks/gate_coverage_20260912 (Phase 0 deliverable; asserted by AC-3)",
      },
      expected: {
        case_count: pending.length,
        stats: {
          tests: real.stats.tests,
          passes: real.stats.passes,
          pending: real.stats.pending,
          failures: real.stats.failures,
        },
      },
      by_spec_file: Object.fromEntries(
        Object.entries(bySpec)
          .sort((a, b) => a[0].localeCompare(b[0]))
          .map(([f, titles]) => [f, { cases: titles.length, titles: titles.sort() }]),
      ),
    };
    // Self-check: the map must agree with the run's own stats, or it is lying in the same way the
    // dry-run pending count does. Fail loudly rather than writing a reassuring zero.
    if (pending.length !== real.stats.pending) {
      throw new Error(
        `pending map says ${pending.length} but the run's stats say ${real.stats.pending} — ` +
          "the reporter shape changed; fix this reader before trusting the map",
      );
    }
    fs.writeFileSync(PENDING_OUT, JSON.stringify(map, null, 2) + "\n");
    console.log(`wrote ${path.relative(ROOT, PENDING_OUT)}: ${pending.length} pending cases`);
  }
}

main();
